# Name of the Spring Boot application
spring.application.name=GenieAi

# Gemini API key
# Used to connect your application with Gemini AI
gemini.api.key=${GEMINI_API_KEY}

# Application will run on port 8080
server.port=8080

# Allows the application to accept connections from other devices
server.address=0.0.0.0


# ==============================
# MySQL Configuration
# ==============================

# MySQL database URL
# Database name is "ecomm"
spring.datasource.url=jdbc:mysql://localhost:3306/ecomm

# MySQL username
spring.datasource.username=root

# MySQL password
spring.datasource.password=Gyana@2005


# ==============================
# JPA + Hibernate Configuration
# ==============================

# Tells Hibernate that we are using MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Automatically updates database tables based on your Entity classes
spring.jpa.hibernate.ddl-auto=update

# Shows SQL queries in the console
spring.jpa.show-sql=true

# Makes SQL queries easier to read
spring.jpa.properties.hibernate.format_sql=true